export const FETCH_LOGIN = 'FETCH_LOGIN'
export const LOGOUT = 'LOGOUT'
export const SHOW_SPINNER = 'SHOW_SPINNER'
export const HIDE_SPINNER = 'HIDE_SPINNER'
export const IS_AUTH_REDUX = 'IS_AUTH_REDUX'
